workspace:
  clean: all

steps:
- checkout: self
  clean: true
  
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7.x'
    architecture: 'x64'

- script: python -m pip install --upgrade pip
  displayName: 'Install/Upgrade pip'

- script: pip uninstall -y edk2_pytool_library
  displayName: 'Remove existing version of self'

- script: pip install --upgrade -r requirements.txt
  displayName: 'Install requirements'

- script: pip install -e .
  displayName: 'Install from Source'

- script: pytest -v --junitxml=test.junit.xml --html=pytest_report.html --self-contained-html --cov=edk2toollib --cov-report html:cov_html --cov-report xml:cov.xml --cov-config .coveragerc
  displayName: 'Run UnitTests'

# Publish Test Results to Azure Pipelines/TFS
- task: PublishTestResults@2
  displayName: 'Publish junit test results'
  continueOnError: true
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit' # Options: JUnit, NUnit, VSTest, xUnit
    testResultsFiles: 'test.junit.xml' 
    mergeTestResults: true # Optional
    publishRunAttachments: true # Optional

# Publish Build Artifacts
# Publish build artifacts to Azure Pipelines/TFS or a file share
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'pytest_report.html' 
    artifactName: 'Edk2_pytool_library unit test report' 
  continueOnError: true
  condition: succeededOrFailed()

# Publish Code Coverage Results
# Publish Cobertura code coverage results
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'cobertura' # Options: cobertura, jaCoCo
    summaryFileLocation: $(System.DefaultWorkingDirectory)/cov.xml
    reportDirectory: $(System.DefaultWorkingDirectory)/cov_html
  condition: succeededOrFailed()

- script: flake8 .
  displayName: 'Run flake8'
  condition: succeededOrFailed()

# Only capture and archive the lint log on failures.
- script: flake8 . > flake8.err.log
  displayName: 'Capture flake8 failures'
  condition: Failed()

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'flake8.err.log' 
    artifactName: 'Flake8 Error log file'
  continueOnError: true
  condition: Failed()

- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'BasicDevTests.py'
    #script: # Required when scriptSource == Inline
    #arguments: # Optional
    #pythonInterpreter: # Optional
    #workingDirectory: # Optional
    #failOnStderr: false # Optional
  displayName: 'Check basic file and folder tests'
  condition: succeededOrFailed()

- task: mspremier.BuildQualityChecks.QualityChecks-task.BuildQualityChecks@5
  displayName: 'Check code coverage metrics'
  inputs:
    checkWarnings: false
    showStatistics: true
    checkCoverage: true
    coverageFailOption: fixed
    coverageType: branches
    buildConfiguration: '$(BuildConfiguration)'
    buildPlatform: '$(BuildPlatform)'
    explicitFilter: true
    baseDefinitionId: 3
    baseRepoId: '21e399f7-aba6-4c72-a5f5-2bcc7b38a0cf'
    baseBranchRef: refs/heads/master
    runTitle: 'Run Title'
