
site_name: Edk2 Pytools Library Mu
repo_url: https://github.com/tianocore/edk2-pytool-library
copyright: Copyright (c) Microsoft.  All rights reserved
site_description: "edk2-pytool-library Documentation"
site_url: 'https://github.com/tianocore/edk2-pytool-library'
plugins:
    - search
    - macros

theme:
  name: 'material'
  custom_dir: 'theme'
  logo: 'img/mu.png'
  palette:
    primary: 'indigo'
    accent: 'indigo'

#
# Material theme adds additional capabilities
#
markdown_extensions:
  - admonition
  - codehilite
  - meta
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true

nav:
  - Home: 'readme.md'
  - License: 'license.txt'
  #AUTOGENERATED CONTENT WILL BE ADDED HERE